<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {{ $title ?? config('app.name', 'Cazhoo') }}
    </title>
    <style>
        @page {
            margin: 0cm 0cm;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'figtree', sans-serif;
        }

        body {
            margin: 20pt;
        }

        header {
            margin-bottom: 10pt;
        }

        header img {
            width: 40pt;
            height: 40pt;
            float: left;
        }

        header h1 {
            margin-top: 0pt;
            margin-left: 50pt;
            font-size: 16pt;
            color: #333;
            text-transform: uppercase;
        }

        header p {
            margin-top: 8pt;
            margin-left: 50pt;
            font-size: 10pt;
            color: #333;
            text-transform: uppercase;
            letter-spacing: 1.2px;
            word-spacing: 4px;
        }

        header hr {
            margin-top: 10pt;
            border: 0;
            border-top: 1px solid #333;
        }

        footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            color: #333;
        }

        footer p {
            margin-right: 20pt;
            font-size: 10pt;
            text-align: right;
            margin-bottom: 10pt;
        }
    </style>
    @stack('styles')
    @stack('scripts')
</head>

<body>

    <header>
        <img src="{{ public_path('assets/logo.png') }}" alt="Logo">
        <h1>Automated Transport Management System</h1>
        <hr>
    </header>

    {{ $slot }}

    <footer>
        <p>
            Generated by expenses at {{ $generated_at ?? now()->format('Y-m-d H:i:s') }}
        </p>
    </footer>

</body>

</html>
