<!DOCTYPE html>
<html>

<head>
    <title>Expense Report</title>
    <style>
        /* @page {
            margin: 20mm 15mm 30mm 15mm;
        } */

        body {
            font-family: 'Times New Roman', Times, serif, sans-serif;
            font-size: 12px;
            margin: 0;
        }

        h2 {
            text-align: center;
            margin: 20px 0 5px;
        }

        .report-meta {
            text-align: right;
            font-size: 11px;
            margin: 0 20px 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 5px 8px;
            text-align: left;
        }

        th {
            background-color: #f0f0f0;
        }

        .summary {
            width: 100%;
            margin: 0 auto;
            margin-top: 15px;
            font-weight: bold;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            height: 30px;
            padding: 5px 20px;
            font-size: 11px;
            border-top: 1px solid #ccc;
        }

        .footer span {
            display: inline-block;
            width: 49%;
        }

        .footer .left {
            text-align: left;
        }

        .footer .right {
            text-align: right;
        }
    </style>
</head>

<body>

    <h2>Expense Report</h2>

    <div class="report-meta">
        <strong>Report Type:</strong> {{ ucfirst(str_replace('_', ' ', $reportType)) }}<br>
        <strong>Report Period:</strong> {{ $filterRange ?? 'Full Report' }}
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Person</th>
                <th>Date</th>
                <th>Type</th>
                <th>Category</th>
                <th>Amount</th>
                <th>Method</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            @php
                $grandIncome = 0;
                $grandExpense = 0;
                $counter = 1;
            @endphp

            @forelse($expenses as $person => $records)
                @foreach ($records as $exp)
                    @php
                        $amount = $exp->amount;
                        $isIncome = $exp->type === 'income';
                        $isIncome ? ($grandIncome += $amount) : ($grandExpense += $amount);
                    @endphp
                    <tr>
                        <td>{{ $counter++ }}</td>
                        <td>{{ $person }}</td>
                        <td>{{ \Carbon\Carbon::parse($exp->date)->format('d-m-Y') }}</td>
                        <td>{{ ucfirst($exp->type) }}</td>
                        <td>{{ $exp->category->name ?? 'N/A' }}</td>
                        <td>{{ number_format($amount, 2) }}</td>
                        <td>{{ ucfirst($exp->payment_method) }}</td>
                        <td>
                            @php $j = 1; @endphp
                            @foreach (explode('#', $exp->note) as $note)
                                @if (trim($note) !== '')
                                    {{ $j++ }}. {{ trim($note) }}<br>
                                @endif
                            @endforeach
                        </td>
                    </tr>
                @endforeach
            @empty
                <tr>
                    <td colspan="8" style="text-align:center;">No records found for this period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <p>Total Income: {{ number_format($grandIncome, 2) }}</p>
        <p>Total Expense:{{ number_format($grandExpense, 2) }}</p>
    </div>

    <div class="footer">
        <span class="left">
            Generated by: {{ auth()->user()->name ?? 'System' }}
        </span>
        <span class="right">
            Generated on: {{ \Carbon\Carbon::now()->format('d-m-Y h:i A') }}
        </span>
    </div>
</body>

</html>
