<!DOCTYPE html>
<html>
<head>
    <title>Expense Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }

        h2 {
            text-align: center;
            margin-bottom: 10px;
        }

        .report-meta {
            text-align: right;
            font-size: 11px;
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #000;
            padding: 6px 8px;
            text-align: left;
        }

        th {
            background-color: #f0f0f0;
        }

        .footer {
            margin-top: 20px;
            font-size: 11px;
            text-align: right;
            border-top: 1px solid #ccc;
            padding-top: 5px;
        }

        .note-content {
            white-space: pre-line;
        }
    </style>
</head>
<body>
    <h2>Expense Report</h2>

    <div class="report-meta">
        <strong>Report Period:</strong>
        @if($filterRange)
            {{ $filterRange }}
        @else
            Full Report
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Type</th>
                <th>Category</th>
                <th>Amount</th>
                <th>Method</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($expenses as $exp)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ \Carbon\Carbon::parse($exp->date)->format('d-m-Y') }}</td>
                    <td>{{ ucfirst($exp->type) }}</td>
                    <td>{{ $exp->category->name ?? 'N/A' }}</td>
                    <td>{{ number_format($exp->amount, 2) }}</td>
                    <td>{{ ucfirst($exp->payment_method) }}</td>
                    <td >
                        @php $i = 1; @endphp
                        @foreach(explode('#', $exp->note) as $note)
                            @if(trim($note) !== '')
                                <div class="mb-1">{{ $i++ }}. {{ trim($note) }}</div>
                            @endif
                        @endforeach
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center;">No records found for this period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer" style="position: fixed; bottom: 10px; left: 0; right: 0; width: 100%;">
        <span style="text-align: left;">
            Generated by: {{ auth()->user()->name ?? 'System' }}
        </span>
        <span style="text-align: right;">
            Generated on: {{ \Carbon\Carbon::now()->format('d-m-Y h:i A') }}
        </span>
    </div>
</body>
</html>
