<!DOCTYPE html>
<html>

<head>
    <title>Expense Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            margin: 20px;
        }

        h2 {
            text-align: center;
            margin-bottom: 5px;
        }

        .report-meta {
            text-align: right;
            font-size: 11px;
            margin-bottom: 15px;
        }

        .person-title {
            font-size: 14px;
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 5px 8px;
            text-align: left;
        }

        th {
            background-color: #f0f0f0;
        }

        .total-row {
            font-weight: bold;
            background-color: #e8e8e8;
        }

        .footer {
            position: fixed;
            bottom: 10px;
            left: 0;
            right: 0;
            width: 100%;
            font-size: 11px;
            text-align: right;
            border-top: 1px solid #ccc;
            padding-top: 5px;
        }
    </style>
</head>

<body>

    <h2>Expense Report</h2>

    <div class="report-meta">
        <strong>Report Type:</strong> {{ ucfirst(str_replace('_', ' ', $reportType)) }}<br>
        <strong>Report Period:</strong> {{ $filterRange ?? 'Full Report' }}
    </div>

    @php
        $grandIncome = 0;
        $grandExpense = 0;
    @endphp

    @forelse($expenses as $personName => $list)
        <div class="person-title">Person: {{ $personName }}</div>

        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Type</th>
                    <th>Category</th>
                    <th>Amount</th>
                    <th>Method</th>
                    <th>Note</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $totalIncome = 0;
                    $totalExpense = 0;
                @endphp

                @foreach ($list as $i => $exp)
                    @php
                        $isIncome = $exp->type === 'income';
                        $amount = $exp->amount;
                        if ($isIncome) {
                            $totalIncome += $amount;
                            $grandIncome += $amount;
                        } else {
                            $totalExpense += $amount;
                            $grandExpense += $amount;
                        }
                    @endphp
                    <tr>
                        <td>{{ $i + 1 }}</td>
                        <td>{{ \Carbon\Carbon::parse($exp->date)->format('d-m-Y') }}</td>
                        <td>{{ ucfirst($exp->type) }}</td>
                        <td>{{ $exp->category->name ?? 'N/A' }}</td>
                        <td>{{ number_format($amount, 2) }}</td>
                        <td>{{ ucfirst($exp->payment_method) }}</td>
                        <td>
                            @php $j = 1; @endphp
                            @foreach (explode('#', $exp->note) as $note)
                                @if (trim($note) !== '')
                                    {{ $j++ }}. {{ trim($note) }}<br>
                                @endif
                            @endforeach
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
    @empty
        <p style="text-align:center;">No records found for this period.</p>
    @endforelse

    <hr>

    <h3 style="text-align: right;">
        Total Income: ₹{{ number_format($grandIncome, 2) }} |
        Expense: ₹{{ number_format($grandExpense, 2) }}
    </h3>

    <div class="footer">
        <span style="float: left;">
            Generated by: {{ auth()->user()->name ?? 'System' }}
        </span>
        <span style="float: right;">
            Generated on: {{ \Carbon\Carbon::now()->format('d-m-Y h:i A') }}
        </span>
    </div>
</body>

</html>
