<!DOCTYPE html>
<html>

<head>
    <title>Expense Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            margin: 20px;
        }

        h2 {
            text-align: center;
            margin-bottom: 5px;
        }

        .report-meta {
            text-align: right;
            font-size: 11px;
            margin-bottom: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 5px 8px;
            text-align: left;
        }

        th {
            background-color: #f0f0f0;
        }

        .total-row {
            font-weight: bold;
            background-color: #e8e8e8;
        }

        .footer {
            position: fixed;
            bottom: 10px;
            left: 0;
            right: 0;
            width: 100%;
            font-size: 11px;
            text-align: right;
            border-top: 1px solid #ccc;
            padding-top: 5px;
        }
    </style>
</head>

<body>

    <h2>Expense Report</h2>

    <div class="report-meta">
        <strong>Report Type:</strong> {{ ucfirst(str_replace('_', ' ', $reportType)) }}<br>
        <strong>Report Period:</strong> {{ $filterRange ?? 'Full Report' }}
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Person</th>
                <th>Date</th>
                <th>Type</th>
                <th>Category</th>
                <th>Amount</th>
                <th>Method</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            @php
                $grandIncome = 0;
                $grandExpense = 0;
                $counter = 1;
            @endphp

            @forelse($expenses as $person => $records)
                @foreach ($records as $exp)
                    @php
                        $amount = $exp->amount;
                        $isIncome = $exp->type === 'income';
                        $isIncome ? ($grandIncome += $amount) : ($grandExpense += $amount);
                    @endphp
                    <tr>
                        <td>{{ $counter++ }}</td>
                        <td>{{ $person }}</td>
                        <td>{{ \Carbon\Carbon::parse($exp->date)->format('d-m-Y') }}</td>
                        <td>{{ ucfirst($exp->type) }}</td>
                        <td>{{ $exp->category->name ?? 'N/A' }}</td>
                        <td>{{ number_format($amount, 2) }}</td>
                        <td>{{ ucfirst($exp->payment_method) }}</td>
                        <td>
                            @php $j = 1; @endphp
                            @foreach (explode('#', $exp->note) as $note)
                                @if (trim($note) !== '')
                                    {{ $j++ }}. {{ trim($note) }}<br>
                                @endif
                            @endforeach
                        </td>
                    </tr>
                @endforeach
            @empty
                <tr>
                    <td colspan="8" style="text-align:center;">No records found for this period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <strong>Summary:</strong><br>
        <span style="font-weight: bold;">Total Income:</span> ₹{{ number_format($grandIncome, 2) }}<br>
        <span style="font-weight: bold;">Total Expense:</span> ₹{{ number_format($grandExpense, 2) }}<br>
    </div>

    <div class="footer">
        <span style="float: left;">
            Generated by: {{ auth()->user()->name ?? 'System' }}
        </span>
        <span style="float: right;">
            Generated on: {{ \Carbon\Carbon::now()->format('d-m-Y h:i A') }}
        </span>
    </div>
</body>

</html>
