<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ $title ?? 'Duo Dev Expenses Report' }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'DejaVu Sans', sans-serif;
            font-family: DejaVu Sans, sans-serif;
        }

        body main {
            font-size: 12px;
            color: #333;
            margin: 20px;
        }

        .pdf-header {
            text-align: center;
            background-color: #f9f9f9;
            padding: 0 10px;
            border-bottom: 1px solid #ccc;
            margin-bottom: 20px;
        }

        .pdf-header table {
            width: 100%;
            border-collapse: collapse;
        }

        .pdf-header td {
            padding: 8px;
            vertical-align: middle;
            border: none;
            width: auto;
        }

        .pdf-header img {
            max-height: 30px;
            vertical-align: middle;
        }

        .pdf-header td:nth-child(1) {
            width: 25px;
        }

        .pdf-header td:first-child,
        .pdf-header td:nth-child(2) {
            font-size: 12px;
            text-align: left
        }

        .pdf-header td:last-child {
            text-align: right;
            font-size: 12px;
            color: #666;
        }

        .pdf-footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 8px 0;
            font-size: 12px;
            color: #666;
            text-align: center;
            background-color: #f9f9f9;
            border-top: 1px solid #ccc;
        }
    </style>
</head>

<body>
    <header class="pdf-header">
        <table>
            <tr>
                <td>
                    <img src="{{ public_path('assets\\logo.png') }}" alt="Duo Dev Expenses Logo">
                </td>
                <td>
                    Duo Dev Expenses <br>
                    Powered by Duo Dev Technologies
                </td>
                <td>
                    Generated by {{ Auth::user()->name ?? 'Guest' }} on {{ now()->format('d M Y H:i') }}
                </td>
            </tr>
        </table>
    </header>


    <main>
        {{ $slot }}
    </main>
</body>

</html>
