<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ $title ?? 'Duo Dev Expenses Report' }}</title>
    <style>

        @page {
            margin: 20px;
        }
        
        * {
            padding: 0;
            box-sizing: border-box;
            font-family: 'DejaVu Sans', sans-serif;
        }

        body {
            width: 100%;
            height: 100%;
            font-family: 'DejaVu Sans', sans-serif;
            background-color: #fff;
        }

        body main {
            font-size: 12px;
            color: #333;
        }

        .pdf-header {
            padding: 0 10px;
            margin: 0 0 20px 0;
        }

        .pdf-header table {
            width: 100%;
            border-collapse: collapse;
        }

        .pdf-header td {
            padding: 8px;
            vertical-align: middle;
            border: none;
            width: auto;
        }

        .pdf-header img {
            max-height: 30px;
            vertical-align: middle;
        }

        .pdf-header td:nth-child(1) {
            width: 25px;
        }

        .pdf-header td:first-child,
        .pdf-header td:nth-child(2) {
            font-size: 12px;
            text-align: left
        }

        .pdf-header td:last-child {
            text-align: right;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>

<body>
    <header class="pdf-header">
        <table>
            <tr>
                <td>
                    <img src="https://expenses.duodev.in/assets/logo.png" alt="Duo Dev Expenses Logo">
                </td>
                <td>
                    Duo Dev Expenses <br>
                    Powered by Duo Dev Technologies
                </td>
                <td>
                    Generated by {{ Auth::user()->name ?? 'Guest' }} on {{ now()->format('d M Y H:i') }}
                </td>
            </tr>
        </table>
    </header>


    <main>
        {{ $slot }}
    </main>
</body>

</html>
